name: test
description: A new Flutter project.
version: 1.0.0+1
environment: 
  sdk: '>=2.12.0 <3.0.0'
dependencies: 
  flutter: 
    sdk: flutter
  get: ^4.6.6
  connectivity_plus: ^5.0.2
  shared_preferences: ^2.2.2
  cached_network_image: ^3.3.0
  flutter_svg: ^2.0.9
  easy_date_timeline: ^1.0.2
  outline_gradient_button: ^2.0.1+1
  carousel_slider: ^4.2.1
  google_maps_flutter: ^2.5.0
  intl: ^0.19.0
dev_dependencies: 
  flutter_test: 
    sdk: flutter
flutter: 
  uses-material-design: true
  assets: 
    - assets/
    - assets/images/
  fonts: 
    - family: Noto Sans JP
      fonts: 
        - asset: assets/fonts/NotoSansJPMedium.ttf
          weight: 500
        - asset: assets/fonts/NotoSansJPBold.ttf
          weight: 700
        - asset: assets/fonts/NotoSansJPRegular.ttf
          weight: 400
